### ISSUE TITLE
Regarding choice of framework

### ISSUE THREAD

**Issue by ErikBjare** [Dsek-LTH/Website#1]
I saw that @Mattemagikern used some kind of React init in this project.

I'd just like to take the opportunity this early in development to have a discussion about which framework we should pick for the site.

React is a good framework for advanced single page applications, but it might be a bit overkill if much or most of the content is static. I'd suggest starting with something simple like a static site generator (Jekyll is pretty good and I've used it for several sites myself) and if we later need dynamic content we could introduce something like React in the parts where needed.

Some other points:

 - Starting with React might lead to unnecessary complexity.
 - React has a somewhat steep learning curve, if we want to encourage contributions that might be a no-no.

It's a lot easier to go from a static site generator to React/Vue.js/etc than vice versa.

**Comment by ErikBjare** [comment]
So... I guess you guys are going with React?

**Comment by VictorWinberg** [comment]
Yeah booi, react is love ;)

**Comment by ErikBjare** [comment]
It makes me cry a little. I think react is too much of a commitment/lock-in and a burden on new contributors. 

But I guess the work has started and no one else is interested in in using anything else so I'm closing.
