### ISSUE TITLE
Regarding branching strategy

### ISSUE THREAD

**Issue by Oscar-Rydh** [Dsek-LTH/Website#4]
I think we should consider master as the dev branch, instead of explicitly having a dev branch. Then everyone can always just clone master and do pull requests to it.

**Comment by martinjohansson93** [comment]
I agree with this having the development as the master branch and a separate "production" branch that is the current version of the website.

**Comment by eHammarstrom** [comment]
dev has been merged with master, issue may close when a production branch has been produced. This at a later date when we are somewhat production ready perhaps

**Comment by OskarDamkjaer** [comment]
Could reference of a "dev" branch now be removed from the readme?

**Comment by ErikBjare** [comment]
I think this issue should be closed before a production branch is created.

Not much point in waiting, it's not like we'll forget to create a stable branch :smile:
