### ISSUE TITLE
Create a basic .travis.yml

### ISSUE THREAD

**Issue by ErikBjare** [Dsek-LTH/Website#9]
Right now the build fails since missing Travis conf leads to Travis assuming the project is a Ruby project. It subsequently fails when it fails to find a Rakefile. 

I would make a PR, unfortunately I'm traveling (without my computer).

Simply putting the following in the file would do it for now:

    language: node_js

**Comment by eHammarstrom** [comment]
Since we're using `create-react-app`, this [.travis.yml](https://github.com/facebookincubator/create-react-app/blob/master/.travis.yml) might be of interest.

**Comment by ErikBjare** [comment]
Nice find, looks good to me.
